- app.js
:koala:
Lotus seems to display dates in UTC, so user data app should do so as well.
- [JIRA OFFAPPS-362](https://zendesk.atlassian.net/browse/OFFAPPS-362)
- N/A
> OFFAPPS-362 Display dates in UTC

- app.js
:koala:
This PR eliminates the duplicated API calls made when switching ticket tabs.
- [JIRA OFFAPPS-366](https://zendesk.atlassian.net/browse/OFFAPPS-366)
- N/A
> OFFAPPS-366 Fix unintended reload of APIs

- README.md
- app.js
- templates/display.hdbs
:koala:
Makes fields you can't edit not editable.
- Jira link: https://zendesk.atlassian.net/browse/OFFAPPS-453
- ~~There's a race condition here. If we try to render the view before the customRoles request returns we'll default to being unable to edit organisation fields. Can fix this by making it a promise that blocks rendering the view.~~
> handle role

- README.md
@zendesk/quokka now switching on for production
> prod readme

- app.js
:koala:
org notes editing is a separate permission.
- Jira link: https://zendesk.atlassian.net/browse/OFFAPPS-453
- None
> OFFAPPS-453 split out notes permission from organization editing

- app.js
:koala:
Third time's a charm
- Jira link: https://zendesk.atlassian.net/browse/OFFAPPS-453
- None
> OFFAPPS-453 set fields in the right order, make user fields editable conditionally

- app.js
:koala:
- Jira link: https://zendesk.atlassian.net/browse/OFFAPPS-453
- This PR has a genuine risk of being QA approved.
> OFFAPPS-453 agents can edit fields

- app.js
fixed newlines for agents (not admins)
- Jira link: https://zendesk.atlassian.net/browse/OFFAPPS-535
- None
> OFFAPPS-535 fixed newlines for agents (not admins)

- app.css
:koala:
This was bugging me...
**before**
**after**
/cc @zendesk/quokka @benhass 
- None
> Align social icons within the width of the rest of the content

- app.css
:koala:
added overflow:auto to css to fix long email addresses flowing over the boundary of app
Before: 
After:
/cc @zendesk/vegemite @zendesk/wombat 
- Jira link: https://zendesk.atlassian.net/browse/OFFAPPS-626
- None
> [OFFAPPS-626] CSS Fix

- app.js
:bear:
/cc @zendesk/wombat  
This PR fixes the inconsistency when displaying a date field across different browsers. 
* JIRA: https://zendesk.atlassian.net/browse/OFFAPPS-662
* Zendesk Ticket: https://support.zendesk.com/agent/tickets/1437825
* [ low ] - Displays a date field incorrectly.
> [OFFAPPS-662]fix date format inconsistency across different browsers

- app.css
- app.js
- lib/requests.js
:v:
/cc @zendesk/vegemite
- Reduces the number of requests being made by the app
- Ensures locales, user fields and organisation fields are only fetched in the initial instance of the app in a session
- Minor CSS changes to make spacing between tags consistent with tags in the left hand column:
before![zendesk_support_-_agent 2](https://cloud.githubusercontent.com/assets/8508387/22873120/e9495428-f211-11e6-9566-13ec882080ba.png)
after![zendesk_support_-_agent](https://cloud.githubusercontent.com/assets/8508387/22873131/fcc8d58c-f211-11e6-9016-d630a3dcf7e6.png)
* JIRA: https://zendesk.atlassian.net/browse/AF-567
* [medium] User Data app stops loading correctly
* [low] Notes and Details fields don't update correctly
> [AF-567] Reduce the number of API calls made

- app.js
:v:
/cc @zendesk/vegemite
Missed a semicolon
> [AF-567] Fix missing semicolon

- app.js
- templates/display.hdbs
Adding support for links if User Fields
> Adding support for links if User Fields

- app.js
https://zendesk.atlassian.net/browse/AF-720
[low] could break user fields on user data app
> [AF-720] Verify input is string before link check

- src/translations/en.yml
New translations for https://github.com/zendesk/user_data_app/pull/83
> new translations

- spec/app_spec.js
- src/javascript/app.js
- src/javascript/lib/i18n.js
- src/javascript/main.js
- src/templates/display.hdbs
- src/templates/spoke.hdbs
- webpack/stats.js
The links were broken because we are in an iframe. Fixed the urls and events so it works accordingly.
Also sneakily updated the `stats.js` script to the newest version.
Jira: https://zendesk.atlassian.net/browse/OFFAPPS-1025
> [OFFAPPS-1025] Fix hrefs (and update stats script)

- package.json
- src/manifest.json
Quick Thumbs up to correct App Version for Deployment yada yada
Guess we forgot to bump this in our previous deployment
> Correct App Version for deployment

- README.md
- package.json
- src/main.scss
- src/manifest.json
See OFFAPPS-1128 for more details.
Status badges have changed again. So we need to update these in apps.
[JIRA ticket](https://zendesk.atlassian.net/browse/OFFAPPS-1128)
[Design Docs](https://paper.dropbox.com/doc/Color--AWUzvkFKT3eXZbiE1LVAN~82Ag-hKdOUNaJjTkPu9XGuRxY1)
Anyone specific?
Unless there's a good reason not to:
@m-lai 
* [low] Mandy changes them again
> [OFFAPPS-1128] Update status badges to new standards

- spec/app_spec.js
- src/javascript/app.js
- src/templates/display.hdbs
Wrote a new function to generate the hrefs. Changed the template to use this new function. Added tests for the function. Replaced old 'open ticket tab' function to use the new function, to not have this code duplicate.
Go by commit for easier reviewing.
[Zendesk ticket](https://support.zendesk.com/agent/tickets/4265248)
* [low] links broken in user data app
> Generate ticket links function

- spec/app.spec.js
- src/javascript/app.js
- src/javascript/lib/api_helpers.js
Fixed endless loop by breaking the chain.
Fixed `parseNum` function
Added test for `parseNum`
**Go by commit for easier reviewing**
[JIRA ticket](https://zendesk.atlassian.net/browse/OFFAPPS-1181)
* [low] User Data App keeps loading
> [OFFAPPS-1181] Fix loop

- src/javascript/app.js
Race condition caused by api router. Fix by setting default (array)
[JIRA ticket](https://zendesk.atlassian.net/browse/OFFAPPS-XXX)
* [none]
> Fix race condition

- src/javascript/app.js
- src/javascript/lib/helpers.js
- src/templates/spinner.hdbs
When the ticket doesn't have an organization, the app should not display an error.
* [low] User data showing an error about ticket organization.
> No error on no organization

- package.json
- src/javascript/lib/requests.js
- src/manifest.json
Reduce the load from API calls for requested tickets.
[JIRA ticket](https://zendesk.atlassian.net/browse/OFFAPPS-1185)
* [low] Mitigation isn't as much as we'd hoped.
> [OFFAPPS-1185] Exclude count and archived
