zendesk/user_data_app

- app.js
:koala:
take 2
`requester.email.changed` is fired when app is created, somehow
We need to guard it from firing another initialization call to avoid race condition.
Then, it should trigger the re-initialization when the requester email is really changed.
- [JIRA OFFAPPS-366](https://zendesk.atlassian.net/browse/OFFAPPS-366)
- N/A
> OFFAPPS-366 Guard requester email change

- app.js
:koala:
Only pre-set requester email when a requester exists
- [JIRA OFFAPPS-402](https://zendesk.atlassian.net/browse/OFFAPPS-402)
- N/A
> OFFAPPS-402 Fix new ticket side bar

- app.js
:koala: :bug: 
When an organization is set on a Ticket, we should use that organization for display in the app, rather than the user's default organization.  If there is no organization set on the Ticket, the app will fall back to the user's default organization.
- ZAF PR: zendesk/zendesk_app_framework#336
- Jira link: https://zendesk.atlassian.net/browse/OFFAPPS-386
- [MEDIUM] The incorrect organization could be shown in the User Data App, or no organization at all.
> [OFFAPPS-386][ZD909384] Organisation shown should be derived from the ticket not the user

- app.js
:koala:
This optimises for making the least number of requests. Each hit returns 100 tickets and there are 6 possible statuses. We can fetch the count for each status in one hit (makes 6 API calls) or we can fetch the tickets 100 at a time and group them to count. So if there are 701 or more tickets (8 API calls) this PR prefers to search.
We never paginated organisations so org tickets have been left as they were.
- Jira link: https://zendesk.atlassian.net/browse/AF-127
- Slow
> AF-127 use search if there are many tickets

- README.md
Removes unnecessarily gendered pronoun to refer to users. Per [alex](http://alexjs.com/#demo),
`his may be insensitive, use their, theirs, them instead`
> Remove biased language from readme

- app.css
:v:
/cc @zendesk/vegemite
Since the font in Lotus changed to proxima-nova, the fonts in the User Data app became _really_ small. Updated styles to match the spec below:
Before
After
* JIRA: https://zendesk.atlassian.net/browse/OFFAPPS-775
* Needs to be checked in other browsers.
> [OFFAPPS-775] Style updates for new proxima-nova font changes in lotus

- app.js
- lib/requests.js
:v:
/cc @zendesk/vegemite
Fixes a few bugs introduced in the previous PR (https://github.com/zendesk/user_data_app/pull/64):
* Fixes issue in https://support.zendesk.com/agent/tickets/2264286
* Allows User Field changes to be persisted again
* Makes _Notes_ and _Details_ fields editable again
* Removes error when saving User Fields in ZAT
* JIRA: https://zendesk.atlassian.net/browse/AF-567
* [low] User Data app doesn't correctly save settings
> [AF-567] Fix various bugs

- package-lock.json
- package.json
- spec/app_spec.js
- src/javascript/lib/requests.js
- src/javascript/main.js
- webpack.config.js
- webpack/stats.js
- webpack/translations-loader.js
A couple of new additions.
1) Fixed bug that only happened in production: saving the settings didn't work properly because the API doesn't support booleans.
2) Added the new `stats.js` script to analyse the build webpack outputs. In addition I added a lodash plugin to save a whopping 20kb of the gzip version (80kb uncompressed).
3) Fix linter remarks about single/double quotes
4) Added default value for `env`
JIRA: https://zendesk.atlassian.net/browse/OFFAPPS-978
cc @zendesk/apps-migration @zendesk/vegemite
> [OFFAPPS-978] Small fixes

- src/javascript/app.js
[OFFAPPS-1027] Fix Custom User Field to show Title instead of Tag
When using this app, the custom dropdown field shows the tag, not the title. A fix has been implemented to show the title instead of tag.
trial and error then BOOM!
<details>
<summary>Undefined</summary>
</details>
<details>
<summary>Defined</summary>
</details>
[JIRA ticket](https://zendesk.atlassian.net/browse/OFFAPPS-1027)
Chris Sos
<details>
<summary>Admin Settings -> User Fields -> Custom User Field</summary>
</details>
<details>
<summary>App Before - field value showing tag</summary>
</details>
<details>
<summary>App After - field value showing title</summary>
</details>
low
> [OFFAPPS-1027] Fix Custom User Field to show Title instead of Tag

- spec/app_spec.js
- src/javascript/app.js
- src/main.scss
- src/templates/error.hdbs
"No requester" was showing up on tickets that clearly had a requester.
Because the `.catch` function was simply showing the 'no requester' message, independent of the actual error, it caused confusion.
1) Fixed the actual error (cannot call replace on null).
2) Better error message
[JIRA ticket](https://zendesk.atlassian.net/browse/OFFAPPS-1034)
Anyone specific?
Unless there's a good reason not to:
* [low] field isn't showing up correctly.
> [OFFAPPS-1034] Bugfixes for 'no requester'

- src/main.scss
[OFFAPPS-1041] Display blocks of icon in-line
This implementation is to fix the display issues with social media icons.
<details>
<summary>Why? </summary>
Because this other component looks very different ONLY on my local machine.
</details>
Realised that the icons are squashed together. Tried display inline block instead of block.
And then BAAAM! 
[JIRA ticket](https://zendesk.atlassian.net/browse/OFFAPPS-1041)
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
<details>
<summary>After (only Twitter)</summary>
</details>
<details>
<summary>After (only Fb)</summary>
</details>
@sostopher 
low - some UI icon arrangements and changes
> [OFFAPPS-1041] Display blocks of icon in-line

- src/main.scss
- src/templates/admin.hdbs
This is what happens when you talk to a designer about 1 single colour; you end up redoing the whole app.
Redesign
[JIRA ticket](https://zendesk.atlassian.net/browse/OFFAPPS-XXX)
* [HIGH] Chris asking why I did this.
> Different colors

- src/main.scss
[OFFAPPS-1043] Remove width on button to prevent long text overflow
User data app has a configuration page which is accessible via the cog icon at the top right corner. When a user has selected French as their language, the word "Save and go back" is super duper long. As a result, the text overflows out of the button.
- Replicate the bug by assuming into Hiro's Z1 account
- Removing the width allows the button to expend horizontally while containing the text
- Removing padding: 0 allows the use of default padding around the text and the border (outline of button)
[JIRA ticket](https://zendesk.atlassian.net/browse/OFFAPPS-1043)
[Button in Garden](https://garden.zendesk.com/css-components/buttons/)
<details>
<summary>Button Before</summary>
</details>
<details>
<summary>Button …
> [OFFAPPS-1043] Remove width on button

- src/javascript/app.js
[OFFAPPS-1053] Fix redirection 404 bug when clicking on "new ticket" user data app links
There are a few links available within the user data app. These links direct agents to requesters' profile, showing their requested tickets.
<details>
<summary>Available links on User Data App</summary>
</details>
These links do are accessible on existing tickets (submitted tickets) but throws a 404 on new tickets. This is because new tickets do not have a persisted IDs yet. As a result, localStorage(ticketId) is not set. Clicking on the links to ticket/undefined_id will eventually throws a 404.
- As far as I'm aware zaf client doesn't allow access to browser's window.location.url to get new ticket ID to set localStorage(ticketID) and for redirection.
- knowing that localStorage(requester) is …
> Redirect to requester tab when ticketID is undefined

- src/javascript/app.js
- src/javascript/lib/client.js
- src/javascript/lib/requests.js
Agents can't edit all users / organisations details, but it still displayed a textarea. Only display textarea in the cases we can actually edit it.
[JIRA ticket](https://zendesk.atlassian.net/browse/OFFAPPS-1074)
* [low] agents can still edit details that aren't saveable.
> [OFFAPPS-1074] Fix agent edit textarea

- src/javascript/app.js
Previously using the items in the array, but because it's added conditionally that can cause problems. Named the promises and used them accordingly.
[JIRA ticket](https://zendesk.atlassian.net/browse/OFFAPPS-1074)
* [low] user data still not working correctly.
> [OFFAPPS-1074] Fix user data app not loading correctly

- spec/helpers_spec.js
- src/javascript/app.js
- src/javascript/lib/helpers.js
Users have been complaining they can't do 'open in new tab' anymore, so I put the original urls in the link, and preventDefault when you normally click on it. This means you can now use 'open in new tab' and it will work.
[Zendesk ticket](https://support.zendesk.com/agent/tickets/4265248)
* [low] Ticket Links broken.
> Put url in ticket link a href

- .travis.yml
- src/javascript/app.js
- src/templates/tags.hdbs
When doing `client.get('currentUser')` the organizations are an empty array. By explicitly added `client.get('currentUser.organizations')` we always get the correct array.
Additionally removed class, to display tag the same as in support.
[JIRA ticket](https://zendesk.atlassian.net/browse/OFFAPPS-1120)
* [low] Broke edibility of details and/or notes
> [OFFAPPS-1120] Make sure organizations are all there

- package-lock.json
- package.json
- src/javascript/app.js
- src/javascript/lib/requests.js
- src/main.scss
- src/manifest.json
- src/templates/error.hdbs
Removed `is the user editable` logic and rely on the API call.
Fixed UI by using zendesk garden for error messages.
Go by commit for easy reviewing.
[JIRA ticket](https://zendesk.atlassian.net/browse/OFFAPPS-1120)
* [medium] user and/or organisation details/notes can't be edited.
> [OFFAPPS-1120] Rely on API parameter, not our own logic

- .github/pull_request_template.md
- .gitignore
- src/translations/en.yml
[OFFAPPS-1174] Translations for copy email mechanism
Translations for "Copied" and "Copy Email" for [this branch](https://github.com/zendesk/user_data_app/pull/114).
**Updated .gitignore because en.yml was included in git ignore**. 
[JIRA ticket](https://zendesk.atlassian.net/browse/OFFAPPS-1174)
Two screenshots used in src code
@hanli625 
@zendesk/localization
* [low] Missing translations
[OFFAPPS-1174]: https://zendesk.atlassian.net/browse/OFFAPPS-1174
> [OFFAPPS-1174] Translations for copy email mechanism

- src/main.scss
[OFFAPPS-1173] Change SVG colors
Change SVG colors for hover and no hover to GREY-600 or GREY-300
[JIRA ticket](https://zendesk.atlassian.net/browse/OFFAPPS-1173)
[color schemes](https://garden.zendesk.com/css-components/utilities/color/)
Default state
Cog on hover
Expend on hover
Collapse on default
Collapse on hover
Close settings on default
Close settings on hover
* [low] Wrong svg colors
[OFFAPPS-1173]: https://zendesk.atlassian.net/browse/OFFAPPS-1173
> [OFFAPPS-1173] Change SVG colors
